server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: site-service
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:mysql://10.0.0.8:3306/goods_db?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/goods_db?serverTimezone=Asia/Shanghai
    url: jdbc:postgresql://localhost:5432/site_db
    driver-class-name:  org.postgresql.Driver
    username: postgres
    password: a
    validationQuery: SELECT 1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # Locale used for formatting
    time-zone: "GMT+8"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write_dates_as_timestamps: false

upload:
  size: 6
  path: "/Users/lmm/Downloads/uploads"
  types: ".jpg|.png|.gif|.jpeg|.webp"
  token: "jaioscamidamaej"

logging:
  level:
    org.hibernate: DEBUG
    org.springframework: INFO
    com.ming: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

