server:
  port: 6666

spring:
  main:
    allow-circular-references: true
  application:
    name: site-service
  jpa:

  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/site_db
#    url: jdbc:postgresql://192.168.8.16:5432/site_db
    username: postgres
    password: a
    validationQuery: SELECT 1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # Locale used for formatting
    time-zone: "GMT+8"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write_dates_as_timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ming.site.model¡

upload:
  size: 6
  #  path: "/Users/lmm/Downloads/uploads"
  path: /uploads
  types: ".jpg|.png|.gif|.jpeg|.webp"
  token: "jaioscamidamaej"

logging:
  level:
    com.zaxxer: ERROR
    org.apache: ERROR
    org.apache.ibatis: ERROR
    org.springframework: ERROR
    com.ming: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

encrypt:
  method: "RSA"
  publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSUmzJhwI9uEdeBcc85r1nm7ahBgRuLneoryy7pC0kdF5+IZqxTuom/vnitxtXwbb3YPs2nC9dZQs3BiwuokccPHCNkDhnI9rKeq4b4ZNu3e20P/IGsv1Hsaov/kqDzwQP1Qb0Bm945Bdx3wTFkNe1jOhvkDSNARRD+AIJstNkNwIDAQAB"
  privateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJJSbMmHAj24R14FxzzmvWebtqEGBG4ud6ivLLukLSR0Xn4hmrFO6ib++eK3G1fBtvdg+zacL11lCzcGLC6iRxw8cI2QOGcj2sp6rhvhk27d7bQ/8gay/Uexqi/+SoPPBA/VBvQGb3jkF3HfBMWQ17WM6G+QNI0BFEP4Agmy02Q3AgMBAAECgYADq6Wm+IgJ3FGN/j8dO/yMWM+gAnKiAPBnft10Z43qWDD2oQksYXpmOAc0tLsu3GEmm3wxxoE5qos5eiIpmVCHTxTfWA67cKNFGBx7hiKKHOqpVFWq6RwpRNL1B8XPbQFoccLIwGigu5nYWvh40+K/0h1JXDkfYjiyYTznhxwCwQJBALmnYuD+8bRELJ1RGc2SkZ7hkDmhBWcZgSQs0KDdgokDN2pk6DICTA3nq0gQBS2q9rzDlk1JN9KBSqw77AptxW8CQQDJw85a0EWSq4ZKvjuY+flcM6ebVrp6v+bJ339UQ2W9dvcRD0fAR6AIPNzi0Ud+paDH38qzRbXUPsrm+vDPFjm5AkBHaYyOUWK13Zdvt/d97MgY3lj04exLGTNkr9xcVHhWracORNxQCDQrERcAdDEZvO6F85IIDobrcRJBKBeGd2z/AkEArnz059q4YFiQQfF0jx6XxWIysAd4LBHr4Ge1sUS8JvdMQeeqEKKgxp8EE/ATWXaZrmFe5l0CG/TV+p3IRf+dmQJBAKv2bo6524bG7GGy7xGptQgYPyx6LoLuu90fXzGRwkciIx83TRLqFzsnMMjEzoxAPx+h1SbGlElqUS4FU6UqBto="

paypal:
  clientId: "AXfwdAXDOk42sd-sZBKQfFRJlGLwlZGeO0MySL7ZHF35NXcnTgAMS-iS6EJzZfOen9XKuVYma15xxdpO"
  secretKey: "ENe5ddQKPp9KkqWge9EHsz7MYVPt3ow3mjkF4cNc_qy_YwI-5GD0muoM9bES8XTAK5F8DCPbfMd9jovM"
  cancelUrl: "https://api.sunmoon.zone/site/v1/cancel/orderId"
  callbackUrl: "https://api.sunmoon.zone/site/v1/callback/orderId"
  currency: "USD"
  mode: "sandbox"




