server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: site-service
  jpa:

  datasource:
    url: jdbc:postgresql://localhost:5432/site_db
    driver-class-name:  org.postgresql.Driver
    username: postgres
    password: a
    validationQuery: SELECT 1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # Locale used for formatting
    time-zone: "GMT+8"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write_dates_as_timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ming.site.model¡

upload:
  size: 6
  path: "/Users/lmm/Downloads/uploads"
  types: ".jpg|.png|.gif|.jpeg|.webp"
  token: "jaioscamidamaej"

logging:
  level:
    org.apache.ibatis: DEBUG
    org.springframework: INFO
    com.ming: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

