server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: site-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 500KB
      max-file-size: 30MB
      max-request-size: 100MB

  datasource:
    driver-class-name:  org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/site_db
    url: jdbc:postgresql://192.168.1.26:5432/site_db
    username: postgres
    password: a
    validationQuery: SELECT 1
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # Locale used for formatting
    time-zone: "GMT+8"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      write_dates_as_timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ming.site.model

upload:
  size: 6
#  path: "/Users/lmm/Downloads/uploads"
  path: "E:\\downloads\\uploads"
  types: ".jpg|.png|.gif|.jpeg|.webp"
  token: "jaioscamidamaej"

logging:
  level:
    com.zaxxer: INFO
    org.apache: INFO
    org.apache.ibatis: INFO
    org.springframework: INFO
    com.ming: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

encrypt:
  method: "RSA"
  publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCSUmzJhwI9uEdeBcc85r1nm7ahBgRuLneoryy7pC0kdF5+IZqxTuom/vnitxtXwbb3YPs2nC9dZQs3BiwuokccPHCNkDhnI9rKeq4b4ZNu3e20P/IGsv1Hsaov/kqDzwQP1Qb0Bm945Bdx3wTFkNe1jOhvkDSNARRD+AIJstNkNwIDAQAB"
  privateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJJSbMmHAj24R14FxzzmvWebtqEGBG4ud6ivLLukLSR0Xn4hmrFO6ib++eK3G1fBtvdg+zacL11lCzcGLC6iRxw8cI2QOGcj2sp6rhvhk27d7bQ/8gay/Uexqi/+SoPPBA/VBvQGb3jkF3HfBMWQ17WM6G+QNI0BFEP4Agmy02Q3AgMBAAECgYADq6Wm+IgJ3FGN/j8dO/yMWM+gAnKiAPBnft10Z43qWDD2oQksYXpmOAc0tLsu3GEmm3wxxoE5qos5eiIpmVCHTxTfWA67cKNFGBx7hiKKHOqpVFWq6RwpRNL1B8XPbQFoccLIwGigu5nYWvh40+K/0h1JXDkfYjiyYTznhxwCwQJBALmnYuD+8bRELJ1RGc2SkZ7hkDmhBWcZgSQs0KDdgokDN2pk6DICTA3nq0gQBS2q9rzDlk1JN9KBSqw77AptxW8CQQDJw85a0EWSq4ZKvjuY+flcM6ebVrp6v+bJ339UQ2W9dvcRD0fAR6AIPNzi0Ud+paDH38qzRbXUPsrm+vDPFjm5AkBHaYyOUWK13Zdvt/d97MgY3lj04exLGTNkr9xcVHhWracORNxQCDQrERcAdDEZvO6F85IIDobrcRJBKBeGd2z/AkEArnz059q4YFiQQfF0jx6XxWIysAd4LBHr4Ge1sUS8JvdMQeeqEKKgxp8EE/ATWXaZrmFe5l0CG/TV+p3IRf+dmQJBAKv2bo6524bG7GGy7xGptQgYPyx6LoLuu90fXzGRwkciIx83TRLqFzsnMMjEzoxAPx+h1SbGlElqUS4FU6UqBto="

paypal:
  clientId: "AUJYDWHcAvaelmTVB7bpYuvDdPEYwJjC6p-8IRVRU_NTy76M4GJ-HAE4EAqqUARxefoDcbITM5UTaOQd"
  secretKey: "EBbB3_zLwgEJwS43G36jn8_tKEKth9-J12FV89IzMl2yRajRrFfwacl6kZLUEI17zTKZoWxXW1sxGuCC"
  cancelUrl: "http://192.168.1.18:3000/cancel"
  callbackUrl: "http://192.168.1.18:3000/success"
  currency: "USD"
  mode: "sandbox"





